### ISSUE TITLE
Working in sandbox mode, but not working with live.

### ISSUE THREAD

**Issue by hasinoorit** [paypal/merchant-sdk-php#123] opened 2016-10-25 07:18 UTC
Hi.
My SDK is working fine with sandbox. but not working with live version. 
my sdk version 3.9.1 , php  version 5.6 . hosted on godaddy, SSL installed. It is not getting access token.

**Comment by pp-randy** [comment] 2016-11-01 15:41
@hasinoorit would you be able to provide any error messaging you are getting?  A correlation id from an error response would be helpful.

**Comment by pp-randy** [comment] 2016-11-07 15:12
Closing due to inactivity

**Comment by alle** [comment] 2017-01-12 16:55
@pp-randy I would like to re-open this issue. Same running condition as @hasinoorit.
I can give your some correlation ids (all of these are in production environment, not sandbox):
- Error: Operation timed out after 0 milliseconds with 0 out of 0 bytes received, correlation id c65b24ae6a16b 
- Error: Unknown SSL protocol error in connection to api-3t.paypal.com:443, correlation id cf20c80e93ea       
- Error: Unknown SSL protocol error in connection to api-3t.paypal.com:443, correlation id d1fc0f2f9e415      
- Error: Operation timed out after 0 milliseconds with 0 out of 0 bytes received, correlation id ad53593ade2a3 
- Error: Operation timed out after 0 milliseconds with 0 out of 0 bytes received, correlation id b6becde99a294 
- Error: Operation timed out after 0 milliseconds with 0 out of 0 bytes received, correlation id ff30fc5290d2  
- Error: Operation timed out after 0 milliseconds with 0 out of 0 bytes received, correlation id ef9a61aa3ac86 
- Error: Unknown SSL protocol error in connection to api-3t.paypal.com:443, correlation id 1c636a5630efa      
- Error: Operation timed out after 0 milliseconds with 0 out of 0 bytes received, correlation id f1dd0669d7708 
- Error: Operation timed out after 0 milliseconds with 0 out of 0 bytes received, correlation id 9a78e4d16126  
- Error: Operation timed out after 0 milliseconds with 0 out of 0 bytes received, correlation id f90b42573bbb8 
- Error: Operation timed out after 0 milliseconds with 0 out of 0 bytes received, correlation id 41b659797c962 
- Error: Operation timed out after 0 milliseconds with 0 out of 0 bytes received, correlation id 42c6a9afd9ed6 
- Error: Operation timed out after 0 milliseconds with 0 out of 0 bytes received, correlation id bea32fe138d0d 

A note: pinging api-3t.paypal.com returns a timeout error.

**Comment by pp-randy** [comment] 2017-01-12 19:45
Pinging does not work since ICMP packets are dropped.  

The Error you have shows SSL protocol error.  What SSL protocol are you connecting with @alle? I advise ensuring TLS 1.2 for this  https://github.com/paypal/tls-update

**Comment by alle** [comment] 2017-01-13 08:35
I realized that ICMP packets were dropped, it wasn't a reliable evidence.
We are already using TLS 1.2, I already knew that.
Anyway, the above mentioned errors/correlation ids provided were only a sample.
Running with the same conditions, many transactions goes well, while others give that errors. There is no constant on the behaviour.
In order to be sure, I contacted my ISP, who has confirmed to me that there are no traffic restrictions on our server that can block the connections to PayPal, nor "TLS connections" as well.

**Comment by pp-randy** [comment] 2017-01-13 15:40
@alle you're right and I apologize, I missed you saying you had correlation ids initially.  I'll look into them now.

**Comment by pp-randy** [comment] 2017-01-13 17:00
@alle if you are getting a correlation id that means you did receive a response from PayPal.  Is this the actual API response? I looked over some of the logs and it looks like these are good SetExpressCheckout calls.

**Comment by pp-randy** [comment] 2017-01-13 17:15
@alle I don't want to rule out a possible curl issue either since that seems to be the origination of the error message.

**Comment by alle** [comment] 2017-01-16 10:50
@pp-randy We use an up-to-date version of curl with TLS 1.2.
The situation seems normalized, now: we are not getting errors anymore. Meanwhile, nothing has changed on our integration.
Anyway we were getting those errors on correlation ids on the wrong point of the transaction path (you were right).
That does not exclude that those "time out" errors were there.
We reserve to check during the next days if something new comes up.
Meanwhile, we can close this issue, I'll reopen it if need it.

**Comment by pp-randy** [comment] 2017-01-17 14:52
@alle I'm glad you were able to resolve.  Let me know if something comes up.

**Closed by pp-randy** 2017-01-17 14:52 UTC
Labels: question
