### ISSUE TITLE
Warning: Ambiguous class resolution, "PayPal\Auth\OAuthTokenCredential" was found in both

### ISSUE THREAD

**Issue by irwing-reza** [paypal/merchant-sdk-php#117] opened 2016-08-19 22:47 UTC
Generating optimized autoload files
Warning: Ambiguous class resolution, "PayPal\Auth\OAuthTokenCredential" was found in both "vendor/paypal/sdk-core-php/lib/PayPal/Auth/OAuthTokenCredential.php" and "vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php", the first will be used.
Warning: Ambiguous class resolution, "PayPal\Rest\ApiContext" was found in both "vendor/paypal/sdk-core-php/lib/PayPal/Rest/ApiContext.php" and "vendor/paypal/rest-api-sdk-php/lib/PayPal/Rest/ApiContext.php", the first will be used.
Warning: Ambiguous class resolution, "PayPal\Rest\IResource" was found in both "vendor/paypal/sdk-core-php/lib/PayPal/Rest/IResource.php" and "vendor/paypal/rest-api-sdk-php/lib/PayPal/Rest/IResource.php", the first will be used.

On composer i have 
```
"paypal/rest-api-sdk-php": "1.7.*",
"paypal/merchant-sdk-php":"3.8.*"
```

**Comment by jaypatel512** [comment] 2016-08-19 23:32
Duplicate of https://github.com/paypal/sdk-core-php/issues/85

**Closed by jaypatel512** 2016-08-19 23:32 UTC
